dell/csi-baremetal-operator

- controllers/deployment_controller.go
1. Add finalizer to abort csi-CR deletion without operator
2. Concurrent reconciliation is forbidden (some resources updated twice including CR)
> [ISSUE-352] Support CSI uninstall

- pkg/controller.go
- pkg/node.go
Fix args in `livenessprobe` sidecar deployed with `csi-baremetal-controller`
> [ISSUE-356] Fix controller livenessprobe args

- api/v1/components/patcher.go
- api/v1/components/scheduler.go
- charts/csi-baremetal-deployment/templates/configmap/patcher-configmap.yaml
- charts/csi-baremetal-deployment/templates/csi-baremetal_v1_deployment.yaml
- charts/csi-baremetal-deployment/values.yaml
- charts/csi-baremetal-operator/templates/manager.yaml
- charts/csi-baremetal-operator/templates/rbac.yaml
- pkg/csi_deployment.go
- pkg/scheduler_patcher_openshift.go
- increase memory limit
- fix port
- fix rbac
> [ISSUE-417] Fix CSI deployment via Operator on Openshift

- charts/csi-baremetal-deployment/templates/configmap/patcher-configmap.yaml
Fix extender port parameter passed into `schedulerpatcher-config` configmap
Regression from https://github.com/dell/csi-baremetal-operator/pull/39
> [ISSUE-423] Fix incorrect extender port parameter in csi-deployment chart

- go.mod
- pkg/scheduler_patcher_openshift.go
When Extender ConfigMap is already exist Operator skips Scheduler config pathing. As a result configuration might not be fully applied when CSI was uninstalled incorrectly. Thus PVC will stuck in pending state.
Manually tested with pre-installed ConfgiMap:
```
2021-06-24T10:28:43.367Z        INFO    controller-runtime.manager.controller.csi-controller    Starting workers        {"worker count": 1}
2021-06-24T10:28:43.367Z        INFO    controllers.Deployment  Custom resource obtained        {"deployment": "default/csi-baremetal"}
2021-06-24T10:28:43.657Z        INFO    ConfigMap is already patched    {"csi-baremetal": "patcher"}
```
Scheduler was patched:
```
[root@servicenode ~]# kubectl describe scheduler cluster
...
Spec:
Masters Schedulable:  true
Policy:
Name:  scheduler-policy
```
> [ISSUE-436] Always patch Scheduler config on OpenShift

- charts/csi-baremetal-operator/templates/manager.yaml
Need to increase memory limit from 100 to 200 MiB to work on OpenShift.
Tested manually
> [ISSUE-417] Bump memory limit for OpenShift

- api/v1/components/patcher.go
- charts/csi-baremetal-deployment/templates/csi-baremetal_v1_deployment.yaml
- charts/csi-baremetal-deployment/values.yaml
- charts/csi-baremetal-operator/values.yaml
- docs/MANUAL_SCHEDULER_CONFIGURATION.md
- docs/README.md
- pkg/constant/platforms.go
- pkg/patcher/extender_readiness.go
- pkg/patcher/extender_readiness_test.go
- pkg/patcher/patcher_configuration.go
- pkg/patcher/scheduler_patcher.go
- pkg/scheduler_extender.go
Changes to work with third party k8s scheduler extender:
1. Use flag `scheduler.patcher.enable` in addition to platform
2. Add documentation for manual patching
Without patcher:
```
$ helm install csi-baremetal charts/csi-baremetal-deployment ...
$ kubectl get pods
NAME                                             READY   STATUS    RESTARTS   AGE
csi-baremetal-controller-f9b7f4c66-4t8v6         4/4     Running   0          11m
csi-baremetal-node-controller-5648569f77-cwlks   1/1     Running   0          11m
csi-baremetal-node-kernel-5.4-bqs8k              4/4     Running   0          11m
csi-baremetal-node-kernel-5.4-k6r9q              4/4     Running   0          11m
csi-baremetal-node-kernel-5.4-kth4n              4/4     Running   0          11m
csi-baremetal-operator-6fcf7c865b-6qkng …
```
> [ISSUE-500] third party extenders

- main.go
- pkg/acrvalidator/acr_validator.go
- pkg/acrvalidator/acr_validator_test.go
- Add the watcher to check and remove outdated ACRs
- Start it the main as infinite goroutine 
```
user@user-vm ~/g/s/g/dell> ka csi-baremetal/test/app/testlvg/2.yaml
statefulset.apps/web2 created
user@user-vm ~/g/s/g/dell> kg acr
NAME             NAMESPACE   STATUS
default-web2-0   default     REJECTED
default-web2-1   default     REJECTED
default-web2-2   default     REJECTED
user@user-vm ~/g/s/g/dell> kdl -f csi-baremetal/test/app/testlvg/2.yaml
statefulset.apps "web2" deleted
user@user-vm ~/g/s/g/dell> kdl pvc -A --all
persistentvolumeclaim "www-web2-0" deleted
persistentvolumeclaim "www-web2-1" deleted
persistentvolumeclaim "www-web2-2" deleted
persistentvolumeclaim "www1-web2-0" deleted
persistentvolumeclaim "www1-web2-1" deleted
persistentvolumeclaim "www1-web2-2" deleted …
```
> [ISSUE-535] Remove outdated ACRs

- charts/csi-baremetal-deployment/templates/storageclass/nvme-raw-part-sc.yaml
Related changes with https://github.com/dell/csi-baremetal/pull/599
```
user@user-vm ~/g/s/g/dell> kd volume
Name:         pvc-332271f9-7050-4ffc-a58b-bcfe49e55648
Namespace:    default
Labels:       app=nginx
app.kubernetes.io/name=nginx
Annotations:  <none>
API Version:  csi-baremetal.dell.com/v1
Kind:         Volume
Metadata:
Creation Timestamp:  2021-11-09T08:30:18Z
Finalizers:
dell.emc.csi/volume-cleanup
Generation:  4
Managed Fields:
API Version:  csi-baremetal.dell.com/v1
Fields Type:  FieldsV1
fieldsV1:
f:metadata:
f:labels:
.:
f:app:
f:app.kubernetes.io/name:
f:spec:
.:
f:Health:
f:Id:
f:Location:
f:LocationType:
f:Mode:
f:NodeId:
f:OperationalStatus:
f:Size:
f:StorageClass:
f:Usage:
Manager:      controller
Operation:    Update
Time:         2021-11-09T08:30:18Z
API Version: …
```
> [ISSUE-598] Add SC for NVME raw-partitioned mode

- charts/csi-baremetal-deployment/templates/csi-baremetal_v1_deployment.yaml
- charts/csi-baremetal-deployment/values.yaml
- docs/README.md
Signed-off-by: Nikita Mikhnenko <nikita_mikhnenko@dell.com>
storage.k8s.io/v1beta1 CSINode object has been deprecated and was removed in the 1.22 release; storage.k8s.io/v1 CSINode object introduced
To support 1.22 version we should update image for csi-provisioner sidecar of csi-controller
```
nmikhnenko@dev-main:~/work/Dell/go/src/csi-baremetal$ kubectl get nodes
NAME                 STATUS   ROLES                  AGE   VERSION
kind-control-plane   Ready    control-plane,master   31h   v1.22.4
kind-worker          Ready    <none>                 31h   v1.22.4
kind-worker2         Ready    <none>                 31h   v1.22.4
kind-worker3         Ready    <none>                 31h   v1.22.4
kind-worker4         Ready    <none>                 31h   v1.22.4
kind-worker5         Ready …
```
> [ISSUE-637] Support k8s 1.22 version for csi

- charts/csi-baremetal-deployment/templates/csi-baremetal_v1_deployment.yaml
- charts/csi-baremetal-deployment/values.yaml
Signed-off-by: Nikita Mikhnenko <nikita_mikhnenko@dell.com>
Issue dell/csi-baremetal#637
Currently csi-baremetal supports k8s versions: 1.18-1.22 and so there is no need to support deprecated provisioner in charts
```
nmikhnenko@dev-main:~/work/Dell/go/src/csi-baremetal$ kubectl get nodes
NAME                 STATUS   ROLES    AGE    VERSION
kind-control-plane   Ready    master   156m   v1.18.2
kind-worker          Ready    <none>   156m   v1.18.2
kind-worker2         Ready    <none>   156m   v1.18.2
kind-worker3         Ready    <none>   156m   v1.18.2
kind-worker4         Ready    <none>   156m   v1.18.2
kind-worker5         Ready    <none>   156m   v1.18.2
kind-worker6         Ready    <none>   156m   v1.18.2
mikhnenko@dev-main:~/work/Dell/go/src/csi-baremetal$ kubectl get po
NAME …
```
> [ISSUE-637] Removing deprecated provisioner from charts

- .codecov.yml
- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_availablecapacities.yaml
- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_availablecapacityreservations.yaml
- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_drives.yaml
- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_logicalvolumegroups.yaml
- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_nodes.yaml
- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_volumes.yaml
- charts/csi-baremetal-operator/templates/manager.yaml
- controllers/deployment_controller.go
- pkg/common/common.go
- pkg/constant/const.go
- pkg/controller.go
- pkg/node/node_daemonset.go
- pkg/node_controller.go
- pkg/patcher/scheduler_patcher_vanilla.go
- pkg/scheduler_extender.go
- Add full `app.kubernetes.io/component` and short `component` labels
```
user@user-vm:~/go_projects/src/github.com/dell$ for podname in $(kubectl get pods | grep -v NAME | awk '{ print $1 }'); do echo $podname; kubectl describe pod $podname | grep component; done
csi-baremetal-controller-795f56d565-68srg
app.kubernetes.io/component=controller
component=controller
csi-baremetal-node-controller-959df6f67-r4rr8
app.kubernetes.io/component=node-controller
component=node-controller
csi-baremetal-node-kernel-5.4-jddms
app.kubernetes.io/component=node
component=node
csi-baremetal-node-kernel-5.4-z5r26
app.kubernetes.io/component=node
component=node
csi-baremetal-operator-7d7f947fc-dcpjq
app.kubernetes.io/component=operator
component=operator
csi-baremetal-se-patcher-2nj22 …
```
> [ISSUE-712] Add component labels for CSI pods

- api/v1/components/csi.go
- charts/csi-baremetal-deployment/templates/csi-baremetal_v1_deployment.yaml
- charts/csi-baremetal-deployment/values.yaml
- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_deployments.yaml
- pkg/patcher/extender_readiness.go
- pkg/patcher/extender_readiness_test.go
- pkg/patcher/scheduler_patcher.go
- pkg/patcher/scheduler_patcher_openshift.go
- pkg/scheduler_extender.go
1. Check whether extender workable; if unworkable, use another extender
2. Whether to use openshift secondary scheduler depends on detected k8s version
3. Scheduler extender readiness checks whether configuration applied to 2nd scheduler
4. Support CSI install on existing openshift secondary scheduler
5. retryPatchOpenshiftSecondaryScheduler
> Secondary Scheduler Code Enhancement

- pkg/patcher/extender_readiness.go
- pkg/patcher/extender_readiness_test.go
Signed-off-by: Shi, Crane <crane.shi@emc.com>
Fix the issue that Openshift 4.12 Scheduler Extender Sometimes Stuck in Not Ready Status
I have successfully re-deployed CSI using the CSI operator image 1.1.0-114.7b6e96e, built from the latest commit in this PR, multiple times and never see this issue again.
custom CI using this CSI operator image passed: https://asd-ecs-jenkins.isus.emc.com/view/Atlantic/job/csi-custom-ci/1520/
custom acceptance on Openshift 4.12 using this CSI operator image passed: https://asd-ecs-jenkins.isus.emc.com/job/csi-custom-acceptance-goop_a/31/
custom acceptance on Atlantic using this CSI operator image passed: https://asd-ecs-jenkins.isus.emc.com/job/csi-custom-acceptance-tar_a/214/
> [ISSUE-950] Openshift 4.12 Scheduler Extender Sometimes Stuck in Not Ready Status

- api/v1/components/openshift_secondary_scheduler.go
- api/v1/components/scheduler.go
- charts/csi-baremetal-deployment/templates/csi-baremetal_v1_deployment.yaml
- charts/csi-baremetal-deployment/values.yaml
- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_deployments.yaml
- pkg/patcher/extender_readiness.go
- pkg/patcher/scheduler_patcher.go
- pkg/patcher/scheduler_patcher_openshift.go
- pkg/patcher/scheduler_patcher_openshift_test.go
Enhance Openshift 4.12 Support:
a) Make openshift secondary scheduler image use CSI common images repo. Make the openshift secondary scheduler image configurable by helm charts parameters. If the openshift secondary scheduler image not provided externally, csi operator will used the default secondary scheduler image.
b) CSI will not be installed on existing 3rd-party secondary scheduler and the CSI removal also will not remove the existing 3rd-party secondary scheduler.
c) refine the logic of function getSchedulerExtenderIP to wait unitl any scheduler extender working to select new scheduler extender IP
d) refine the logic of function getSchedulerExtenderIP to try to get selected scheduler IP from existing config map before trying to get new scheduler extender IP
When manually deploying …
> [ISSUE-955] Enhance Openshift 4.12 Support

- variables.mk
suggest to use latest kubectl image.
because this image is only used to execute command:
```sh
kubectl replace crd -f /crds
```
This subcommand will not change version by version in kubectl.
> [ISSUE-996] csi-baremetal-pre-upgrade-crds CVES

- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_availablecapacities.yaml
- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_availablecapacityreservations.yaml
- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_drives.yaml
- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_logicalvolumegroups.yaml
- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_nodes.yaml
- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_storagegroups.yaml
- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_volumes.yaml
Refine Storage Group Feature CRD changes:
1) Add storagegroup.status
2) Add immutability validation rule to storagegroup.spec, i.e. block of storagegroup.spec update in crd validation.
3) To support immutablity validation rule in crd generation, upgrade controller-gen version to v0.9.2
Manual test passed.
Custom CI passed: https://asd-ecs-jenkins.isus.emc.com/job/csi-custom-ci/1559/
Custom Acceptance Passed: https://asd-ecs-jenkins.isus.emc.com/job/csi-custom-acceptance-tar_b_ona/36/
> [ISSUE-1018] Refine Storage Group Feature on OBS Release 1.3 Branch

- charts/csi-baremetal-operator/templates/pre-upgrade-crds.yaml
imagePullSecrets element nested under containers instead of directly under spec level.
Upgrade with  Values.global.registrySecret specified.
> [ISSUE-223] Pull secret element misplaced in pre upgrade CRD template

- charts/csi-baremetal-deployment/values.yaml
- deploy/configmap/loopbackmgr-config.yaml
Increase loop device size due to upgrades of the base images to ubuntu 24.04 in csi-baremetal.
Full regression
> Feature [ISSUE-230] increase loop size

- charts/csi-baremetal-deployment/values.yaml
- deploy/configmap/loopbackmgr-config.yaml
Increase min loopback device size due to the upgrade of ubuntu to 24.04 in csi-baremetal.
Full regression
> [ISSUE-230] increase loop size
