- api/v1/components/log.go
- api/v1/components/patcher.go
- config/samples/csi-baremetal_v1_deployment.yaml
- pkg/common.go
- pkg/controller.go
- pkg/node.go
- pkg/scheduler_extender.go
- pkg/scheduler_patcher.go
Use parameters from CR Spec in resources creation:
- NodeSelectors
- LogLevel/Format
- ImageName/Tag/Repo 
> [ISSUE-334] Pass NodeSelectors, LogLevel, ImageName

- Makefile
- config/crd/bases/csi-baremetal.dell.com_availablecapacities.yaml
- config/crd/bases/csi-baremetal.dell.com_availablecapacityreservations.yaml
- config/crd/bases/csi-baremetal.dell.com_drives.yaml
- config/crd/bases/csi-baremetal.dell.com_logicalvolumegroups.yaml
- config/crd/bases/csi-baremetal.dell.com_nodes.yaml
- config/crd/bases/csi-baremetal.dell.com_volumes.yaml
- deploy/configmap/fluent-bit-config-map.yaml
- deploy/configmap/loopbackmgr-config.yaml
- deploy/configmap/patcher-configmap.yaml
- deploy/csidriver/csidriver.yaml
- deploy/rbac/controller-rbac.yaml
- deploy/rbac/csibm-rbac.yaml
- deploy/rbac/node-rbac.yaml
- deploy/rbac/rbac.yaml
- deploy/storageclass/default-sc.yaml
- deploy/storageclass/hdd-sc.yaml
- deploy/storageclass/hddlvg-sc.yaml
- deploy/storageclass/nvme-sc.yaml
- deploy/storageclass/ssd-sc.yaml
- deploy/storageclass/ssdlvg-sc.yaml
- deploy/storageclass/syslvg-sc.yaml
* Add yaml files with CSI resources, temporary hardcoded values
> [ISSUE-328]  Add crd, rbacs configmaps and SCs

- .github/workflows/pr.yml
Add basic buld and lint checks on PR to master and master commit
https://github.com/painhardcore/csi-baremetal-operator/runs/2191463500?check_suite_focus=true
> [ISSUE-337] Add build and linter checks in PR validation

- pkg/controller.go
Add gRPC timeout to provisioner
> [ISSUE-360] set provisionerTimeout

- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_availablecapacityreservations.yaml
> [ISSUE-345] ACR CRD updated

- charts/csi-baremetal-deployment/Chart.yaml
- charts/csi-baremetal-operator/Chart.yaml
Update version to 0.2.0
Not applicable
> [ISSUE-377] Update version to 0.2.0

- Makefile
- charts/csi-baremetal-operator/values.yaml
- variables.mk
Add variables.mk with versions.
Add image path
Add make version
> [Issue-372] prepare makefile to build job

- charts/csi-baremetal-operator/templates/manager.yaml
- pkg/common.go
- pkg/controller.go
- pkg/node.go
- pkg/node_controller.go
- pkg/scheduler_extender.go
- pkg/scheduler_patcher.go
Ephemeral folder for crashdump
And label for the logging system to detect which release deployed
> [ISSUE-382] Labels for the logging and crashdump folder

- pkg/patcher.go
- pkg/patcher_test.go
- pkg/scheduler_patcher.go
The last commit in #30 brings regression
This PR reverts that commit and adds extra logging
> [ISSUE-373] fix the wrong path in the patcher

- charts/csi-baremetal-deployment/templates/configmap/patcher-configmap.yaml
Configmap values are meant to be hardcoded values. 
manual CI tests
> [ISSUE-373] Fix configmap variables for  the kubeconfig

- pkg/node/node_daemonset.go
Check drivemgr image name to deploy loopbackmgr configmap
> [ISSUE-414] Fix deploy with loopbackmgr and empty registry

- charts/csi-baremetal-deployment/Chart.yaml
- charts/csi-baremetal-operator/Chart.yaml
- variables.mk
> [ISSUE-415] Update version to 0.2.2

- .github/workflows/pr.yml
- Makefile
- docs/README.md
- upload coverage.out to codecov
- add mark to readme
> [ISSUE-459] Integration with codecov.io

- docs/index.yaml
> [ISSUE-477] release v0.3.0-alpha

- api/v1/components/csi.go
- charts/csi-baremetal-deployment/templates/csi-baremetal_v1_deployment.yaml
- charts/csi-baremetal-deployment/values.yaml
- charts/csi-baremetal-operator/templates/manager.yaml
- charts/csi-baremetal-operator/values.yaml
- pkg/common/common.go
- pkg/controller.go
- pkg/node/node_daemonset.go
- pkg/node_controller.go
- pkg/patcher/patcher_configuration.go
- pkg/patcher/scheduler_patcher_vanilla.go
- pkg/scheduler_extender.go
Add ImagePullSecrets by operator.
> [ISSUE-476] Support registry secret in CSI

- docs/index.yaml
Release v0.3.0-beta charts
n/a
> [ISSUE-488] Release v0.3.0-beta

- .github/workflows/pr.yml
- charts/csi-baremetal-deployment/Chart.yaml
- charts/csi-baremetal-operator/Chart.yaml
- variables.mk
Signed-off-by: misanthropicat <misanthr0picat@gmail.com>
Update to version 0.4.0
> Update version to 0.4.0

- api/v1/components/driver.go
- charts/csi-baremetal-deployment/templates/csi-baremetal_v1_deployment.yaml
- pkg/node/node_daemonset.go
Remove alerts configmap support
> [ISSUE-498] Remove alerts configmap mount

- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_availablecapacityreservations.yaml
- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_logicalvolumegroups.yaml
Related changes with https://github.com/dell/csi-baremetal/pull/510
> [ISSUE-509] Add verbose kubectl output for LVG and ACR

- pkg/node/node.go
Related changes with https://github.com/dell/csi-baremetal/pull/513
> [ISSUE-512] Move TopologyID labels deletion into Operator

- docs/index.yaml
> [ISSUE-520] Release CSI 0.4.0-alpha

- pkg/noderemoval/delete_objects.go
Related changes with [ISSUE-511] Fix restore the same node after removal (WIP!)
> [ISSUE-511] Fix restoring the same node after removal

- docs/index.yaml
> [ISSUE-526] Release CSI 0.4.0-beta

- charts/csi-baremetal-deployment/Chart.yaml
- charts/csi-baremetal-operator/Chart.yaml
- variables.mk
Bump CSI Operator version to 0.5.0
> [ISSUE-526] Bump CSI Operator version to 0.5.0

- charts/csi-baremetal-operator/values.yaml
Update pull policy to Always by default and change default tag to green
n/a
> [ISSUE-528] update pull policy and change default tag to green

- charts/csi-baremetal-operator/templates/manager.yaml
- pkg/common/common.go
- pkg/constant/const.go
- pkg/controller.go
- pkg/node/node_daemonset.go
- pkg/node_controller.go
- pkg/noderemoval/controller_test.go
- pkg/patcher/scheduler_patcher_vanilla.go
- pkg/scheduler_extender.go
Add labels on deployments/daemonsets:
```
app: csi-baremetal
app.kubernetes.io/name: csi-baremetal
```
Add labels on pods:
```
name: {{ .Release.Name }}
app: csi-baremetal
app.kubernetes.io/name: csi-baremetal
release: {{ .Release.Name }}
```
Update pod selectors with:
```
name: {{ .Release.Name }}
```
> [ISSUE-533] Update labels on CSI pods

- charts/csi-baremetal-deployment/templates/csi-baremetal_v1_deployment.yaml
- charts/csi-baremetal-deployment/values.yaml
Related changes with https://github.com/dell/csi-baremetal/pull/543
> [ISSUE-538] Update node-driver-registrar sidecar

- docs/CODEOWNERS
> [ISSUE-544] code owners added

- Makefile
- charts/csi-baremetal-deployment/templates/csidriver/csidriver.yaml
- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_availablecapacities.yaml
- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_availablecapacityreservations.yaml
- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_deployments.yaml
- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_drives.yaml
- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_logicalvolumegroups.yaml
- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_nodes.yaml
- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_volumes.yaml
- config/rbac/auth_proxy_client_clusterrole.yaml
- deploy/csidriver/csidriver.yaml
* Generate CRDs
* Update related CRDs
**Dont edit CRDs manually**, use `controller-gen`.
> [ISSUE-553] Update CRDs apiVersion

- charts/csi-baremetal-deployment/templates/csidriver/csidriver.yaml
> [ISSUE-553] Update storage crd template

- charts/csi-baremetal-deployment/Chart.yaml
- charts/csi-baremetal-operator/Chart.yaml
- variables.mk
Update CSI version to 1.1.0
n/a
> [ISSUE-606] Update CSI version to 1.1.0

- docs/PULL_REQUEST_TEMPLATE.md
Checkbox to set project
Documentation change - n/a
> [ISSUE-620] PR template updated to use projects

- .github/workflows/pr.yml
Make `codecov` check pass mandatory
n/a
> [ISSUE-616] block pr merge when UTs code coverage decreased

- charts/csi-baremetal-deployment/templates/configmap/node-config.yaml
- charts/csi-baremetal-deployment/templates/rbac/node-rbac.yaml
- pkg/node/node_daemonset.go
Changes from [[ISSUE-635] Support WBT disabling](https://github.com/dell/csi-baremetal-operator/pull/102)
In https://github.com/dell/csi-baremetal/pull/638
> [ISSUE-635] Support WBT disabling (release)

- docs/index.yaml
Add CSI release 1.0 helm charts
> [ISSUE-664] Add charts to CSI helm repo for 1.0

- controllers/deployment_controller.go
Improving logging in Baremetal CSI Driver and Operator.
> [ISSUE-696] fix redundant logging while watching role/rolebining

- Dockerfile
- Makefile
- variables.mk
Change FROM directive on the fly with make variable
> [ISSUE-721] base image as variable

- api/v1/components/controller.go
- charts/csi-baremetal-deployment/templates/csi-baremetal_v1_deployment.yaml
- charts/csi-baremetal-deployment/values.yaml
- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_deployments.yaml
- pkg/controller.go
Related changes with https://github.com/dell/csi-baremetal/pull/730
```
user@user-vm ~/g/s/g/d/csi-baremetal-operator (bugfix-test-long-reconcile-on-openshift)> 
helm install csi-baremetal ./charts/csi-baremetal-deployment/ --set image.tag=1.1.0-560.ea660fd --set image.pullPolicy=IfNotPresent --set scheduler.patcher.enable=true --set driver.drivemgr.type=loopbackmgr --set driver.drivemgr.deployConfig=true --set driver.log.level=debug --set scheduler.log.level=debug --set nodeController.log.level=debug --set driver.controller.reservation.slowTimeout=30s
```
```
Environment:
POD_IP:                     (v1:status.podIP)
CSI_ENDPOINT:              unix:///csi/csi.sock
LOG_FORMAT:                text
KUBE_NODE_NAME:             (v1:spec.nodeName)
NAMESPACE:                 default …
```
> [ISSUE-732] Pass reservation controller variables

- docs/README.md
Update deployment instructions for GA version
n/a
> [ISSUE-735] update deployment instructions for GA version

- docs/README.md
Add badge with the Go Report
n/a
> [ISSUE-740] Add badge with the Go Report

- charts/csi-baremetal-deployment/values.yaml
Related changes with https://github.com/dell/csi-baremetal/pull/742
[_Testing details_](https://github.com/dell/csi-baremetal/actions/runs/1817092499)
> [ISSUE-702] Bump sidecars versions

- pkg/scheduler_extender.go
Add `nodeselector` option to scheduler-extender
> [ISSUE-761] Add nodeselector option for scheduler-extender

- charts/csi-baremetal-deployment/templates/csidriver/csidriver.yaml
- docs/MIGRATION_BETWEEN_NAMESPACES.md
Add documentation for CSI namespace migration
Related changes - https://github.com/dell/csi-baremetal/pull/807
TBD
> [ISSUE-814] Add documentation for CSI namespace migration

- deploy/monitoring/csi-pod-monitor.yaml
- deploy/monitoring/monitoring-configmap.yaml
- docs/MONITORING_ON_OPENSHIFT.md
Added configs for built-in Prometheus.
Details in corresponding Jira issue.
> [ISSUE-819] Enable monitoring of CSI pods on OpenShift cluster

- docs/MANUAL_SCHEDULER_CONFIGURATION.md
- docs/README.md
Signed-off-by: Dutova <Ann.Dutova@Dell.com>
Due to proposal dell/csi-baremetal#806 need to add steps for manual patching scheduler on k3s
Was already tested in  dell/csi-baremetal#806
> [ISSUE-125] Update operator documentation

- charts/csi-baremetal-deployment/templates/csi-baremetal_v1_deployment.yaml
- charts/csi-baremetal-operator/templates/manager.yaml
- pkg/common/common.go
- pkg/constant/const.go
Signed-off-by: Dutova <Ann.Dutova@Dell.com>
Added new label - `app.kubernetes.io/instance` instead of `release`
```
ubuntu:/Workspace/csi-baremetal-operator # kubectl get pod 
NAME                                             READY   STATUS    RESTARTS   AGE
csi-baremetal-controller-789b56dc67-pxt7v        4/4     Running   0          3m38s
csi-baremetal-node-controller-6c4b49775b-56d7v   1/1     Running   0          3m40s
csi-baremetal-node-kernel-5.4-jxs2b              4/4     Running   2          3m39s
csi-baremetal-node-kernel-5.4-lr9fn              4/4     Running   1          3m39s
csi-baremetal-node-kernel-5.4-s49qv              4/4     Running   0          3m39s
csi-baremetal-operator-69c5988c7c-d26gh          1/1     Running   0          6m13s
csi-baremetal-se-patcher-lcxmg …
```
> [ISSUE-847] Add new instance label 

- .github/workflows/pr.yml
- Update codecov action
- Use tokenless upload
[_Testing details_](https://github.com/dell/csi-baremetal-operator/runs/6473712915?check_suite_focus=true)
> [ISSUE-853] Tokenless codecov reporting

- charts/csi-baremetal-deployment/templates/configmap/node-config.yaml
- Add `4.18.0-305.45.1.el8_4.x86_64` to defaults 
> [ISSUE-888] Update WBT default settings

- pkg/nodeoperations/controller.go
Signed-off-by: Shi, Crane <crane.shi@emc.com>
Clean spam logs of nonexistent node removal and maintenance in every reconcile
> [ISSUE-909] Clean spam logs of node removal and maintenance in every reconcile

- charts/secondary-scheduler-operator/Chart.yaml
- charts/secondary-scheduler-operator/templates/NOTES.txt
- charts/secondary-scheduler-operator/templates/_helpers.tpl
- charts/secondary-scheduler-operator/templates/post-install-job.yaml
- charts/secondary-scheduler-operator/templates/pre-delete-job.yaml
- charts/secondary-scheduler-operator/templates/pre-install-job.yaml
- charts/secondary-scheduler-operator/templates/role.yaml
- charts/secondary-scheduler-operator/templates/rolebinding.yaml
- charts/secondary-scheduler-operator/templates/serviceaccount.yaml
- charts/secondary-scheduler-operator/templates/subscription.yaml
- charts/secondary-scheduler-operator/values.yaml
deploy openshift secondary scheduler operator on openshift 4.10 and above
- [*] Add link to the issue
- [*] Choose Project
> add secondary scheduler operator chart

- api/v1/components/csi.go
- charts/csi-baremetal-deployment/templates/csi-baremetal_v1_deployment.yaml
- charts/csi-baremetal-deployment/values.yaml
- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_deployments.yaml
- charts/csi-baremetal-operator/templates/rbac.yaml
- go.mod
- go.sum
- pkg/common/common.go
- pkg/patcher/extender_readiness.go
- pkg/patcher/scheduler_patcher.go
- pkg/patcher/scheduler_patcher_openshift.go
Add Secondary Scheduler with Scheduler Extender config if openshift second scheduler used
> Add Secondary Scheduler with Scheduler Extender config if openshift second scheduler used

- api/v1/components/csi.go
- charts/csi-baremetal-deployment/templates/csi-baremetal_v1_deployment.yaml
- charts/csi-baremetal-deployment/values.yaml
- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_deployments.yaml
- charts/csi-baremetal-operator/templates/rbac.yaml
- go.mod
- go.sum
- pkg/common/common.go
- pkg/patcher/extender_readiness.go
- pkg/patcher/scheduler_patcher.go
- pkg/patcher/scheduler_patcher_openshift.go
> Feature second scheduler extender

- api/v1/components/csi.go
- charts/csi-baremetal-deployment/templates/csi-baremetal_v1_deployment.yaml
- charts/csi-baremetal-deployment/values.yaml
- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_deployments.yaml
- charts/csi-baremetal-operator/templates/rbac.yaml
- go.mod
- go.sum
- pkg/common/common.go
- pkg/patcher/extender_readiness.go
- pkg/patcher/scheduler_patcher.go
- pkg/patcher/scheduler_patcher_openshift.go
> Second scheduler extender

- pkg/patcher/extender_readiness.go
- pkg/patcher/scheduler_patcher.go
- pkg/patcher/scheduler_patcher_openshift.go
Signed-off-by: Shi, Crane <crane.shi@emc.com>
Refactor Code to Merge SecondaryScheduler Op Code to Openshift Op Code
> Refactor Code to Merge SecondaryScheduler Op Code to Openshift Op Code

- charts/secondary-scheduler-operator/Chart.yaml
- charts/secondary-scheduler-operator/templates/post-install-job.yaml
- charts/secondary-scheduler-operator/templates/pre-delete-job.yaml
- charts/secondary-scheduler-operator/templates/pre-install-job.yaml
- charts/secondary-scheduler-operator/values.yaml
built operator image from branch. 
> use built scheduler operator image

- controllers/deployment_controller.go
- pkg/patcher/extender_readiness.go
- pkg/patcher/extender_readiness_test.go
- pkg/patcher/scheduler_patcher.go
- pkg/patcher/scheduler_patcher_openshift.go
- pkg/patcher/scheduler_patcher_openshift_test.go
Add UT, Refactor Code and Add Secondary Scheduler Pod Event for CSIDeployment Reconcile
> Add UT, Refactor Code and Add Secondary Scheduler Pod Event for CSIDeployment Reconcile

- variables.mk
change version number to 1.2.0
_Provide test details_
> [ISSUE-980] change version number to 1.2.0 for OBS  Epoch release

- pkg/common/update.go
- pkg/controller.go
- pkg/node_controller.go
Fix operator update controllers every reconcile
> [ATL-5895] Fix operator updates controller and node controller in every reconcile call

- variables.mk
> [ISSUE-982] Change version in master to 1.3.0

- charts/csi-baremetal-deployment/Chart.yaml
- charts/csi-baremetal-operator/Chart.yaml
- charts/secondary-scheduler-operator/Chart.yaml
- variables.mk
change version number to 1.4.0.
> [ISSUE-1038] 1.3.0 branched out, change version to 1.4.0.

- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_availablecapacities.yaml
- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_availablecapacityreservations.yaml
- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_drives.yaml
- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_logicalvolumegroups.yaml
- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_nodes.yaml
- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_storagegroups.yaml
- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_volumes.yaml
Refine Storage Group Feature CRD changes:
1) Add storagegroup.status
2) Add immutability validation rule to storagegroup.spec, i.e. block of storagegroup.spec update in crd validation.
3) To support immutablity validation rule in crd generation, upgrade controller-gen version to v0.9.2
Manual test passed.
Custom CI passed: https://asd-ecs-jenkins.isus.emc.com/job/csi-custom-ci/1559/
Custom Acceptance Passed: https://asd-ecs-jenkins.isus.emc.com/job/csi-custom-acceptance-tar_b_ona/36/
> [ISSUE-1018] Refine Storage Group Feature

- .github/workflows/pr.yml
- charts/csi-baremetal-deployment/values.yaml
- pkg/patcher/scheduler_patcher_openshift.go
upgrade secondary scheduler image to v0.26.7. 
```
[root@servicenode ~]# oc get pvc -A
NAMESPACE     NAME                               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS              AGE
xxxxxxxxxx   postgres-ha-postgres-4gpt-pgdata   Bound    pvc-50c0f3bf-d6c2-462c-8f0d-68890cfd5552   16Gi       RWO            csi-baremetal-sc-ssdlvg   3d13h
xxxxxxxxxx   postgres-ha-postgres-4zvf-pgdata   Bound    pvc-cfef8476-ba57-455c-9904-deb1fccfcb59   16Gi       RWO            csi-baremetal-sc-ssdlvg   3d13h
xxxxxxxxxx   postgres-ha-postgres-d54z-pgdata   Bound    pvc-997e0108-cd99-467c-93e3-0aa5966d0e8e   16Gi       RWO            csi-baremetal-sc-ssdlvg   3d13h
xxxxxxxxxx   postgres-ha-repo1                  Bound …
```
> [ISSUE-187] upgrade secondary scheduler image from v0.23.10 to v0.26.7

- charts/csi-baremetal-deployment/Chart.yaml
- charts/csi-baremetal-operator/Chart.yaml
- charts/secondary-scheduler-operator/Chart.yaml
- variables.mk
> [Issue-1061] version 1.5

- variables.mk
Upgrade kubectl to 1.26
All regression tests
> [ISSUE-1063] kubectl upgarde

- charts/csi-baremetal-operator/templates/pre-upgrade-crds.yaml
- charts/csi-baremetal-operator/values.yaml
Providing job's pod annotation placeholder in order to be able to provide additional annotations from values during helm install/upgrade.
Deployment.
> [ISSUE-197] crd job annotation

- .github/workflows/pr.yml
Upgrading go
Full regression tests
> [Issue-1049] fixing cves

- charts/csi-baremetal-deployment/values.yaml
> [ISSUE-1068] Upgrade CSI sidecars

- variables.mk
> [ISSUE-1073] Upgrade kubectl

- docs/README.md
](https://github.com/dell/csi-baremetal-operator/issues/204)
Removing support for Ubuntu and Centos7
NA
> [Issue-204] Removing not suppoerted versions

- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_drives.yaml
> [ISSUE-206] Extend CRD/proto spec for SmartInfo Support

- variables.mk
> [Issue-208] 1.5.1 version

- variables.mk
> [ISSUE-210] Change component version to 1.6.0

- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_drives.yaml
> [ISSUE-212] Remove SmartInfo from kubectl get drives output

- charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_drives.yaml
> [ISSUE-214] Remove SmartInfo from DriveCR

- .github/.codecov.yaml
- charts/csi-baremetal-deployment/values.yaml
- charts/csi-baremetal-operator/templates/rbac.yaml
> [issue-1122] Removing resolved TODOs

- variables.mk
> [ISSUE-219] Set new release version v1.7.0 on master branch

- charts/csi-baremetal-deployment/templates/service/csi-smart-info-backend-svc.yaml
> [ISSUE-228] Add headless service

- charts/csi-baremetal-deployment/values.yaml
- deploy/configmap/loopbackmgr-config.yaml
> [ISSUE-230] Upgrade loopback device size

- variables.mk
Fix CVEs critical/high or CSVV 7+
All acceptance tests
> [ISSUE-234] Fix CVEs in csi-baremetal-pre-upgrade-crds

- .github/workflows/pr.yml
> Issue 1220

- .github/workflows/pr.yml
> [issue-1220] cve fix

- go.mod
- go.sum
> [ISSUE-240] cve fix

- variables.mk
> [issue-1258] cve fixes

- .github/workflows/pr.yml
- charts/csi-baremetal-deployment/values.yaml
> [ISSUE-244] sidecars update

- variables.mk
> [ISSUE-246] Fixing CVEs for csi-baremetal-pre-upgrade-crds

- docs/README.md
Trigger commit renumbering due to helm issues (previous starts with 00).
N/A
> [ISSUE-249] commit renumbering

- .github/workflows/pr.yml
- charts/csi-baremetal-deployment/values.yaml
Upgrading sidecars due to CVEs
Regression tests
> [ISSUE-244] Sidecar images update

- api/v1/components/sidecar.go
- pkg/controller_test.go
- pkg/node_controller_test.go
> [issue-658] node-controller tests

- pkg/node/node_daemonset_test.go
> [ISSUE-658] node daemonset UT

- pkg/node_controller_test.go
- pkg/scheduler_extender_test.go
> [issue-658] ut

- main.go
- pkg/csi_deployment.go
- pkg/csi_deployment_test.go
Adding UT to csi_deployment.py
Regression
> [ISSUE-658] csi deployment UT

- pkg/common/update_test.go
Improving code coverage of the code in update.go file.
N/A
> [ISSUE-658] improving code coverage in update functions

- pkg/common/common_test.go
- pkg/nodeoperations/delete_objects_test.go
Increasing UT coverage in common.go and delete_objects.go.
N/A
> [ISSUE-658] UT coverage increase
